owner: evelode
repo: tiktok-status
 
assignees:
  -  sergeykomlev

sites:
  - name: /getNoWatermarkUrl - Get non watermarked video url
    url: https://tiktok.evelode.com/getNoWatermarkUrl?video_url=https://www.tiktok.com/@therock/video/7106855913906081070%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503 
      - 521
      - 403
      - 0
  - name: /getNoWatermarkUrlByID - Get non watermarked video url by video ID
    url: https://tiktok.evelode.com/getNoWatermarkUrlByID?video_id=7106855913906081070&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 3000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getVideoByID - Get video info by ID
    url: https://tiktok.evelode.com/getVideoByID?video_id=7106855913906081070&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getVideoByUrl - Get video info by URL
    url: https://tiktok.evelode.com/getVideoByUrl?video_url=https://www.tiktok.com/@therock/video/7106855913906081070%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getUnshortenedUrl - Convert short TikTok video URL to full TikTok video URL
    url: https://tiktok.evelode.com/getUnshortenedUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2Ft%2FZTR9YXeWQ%2F&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getCommentsByUrl - Get comments list by video URL
    url: https://tiktok.evelode.com/getCommentsByUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40onerepublic%2Fvideo%2F7141505394869898538%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getCommentsByID - Get comments list by video ID
    url: https://tiktok.evelode.com/getCommentsByID?video_id=7141505394869898538&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /searchUser - Search for user by keyword
    url: https://tiktok.evelode.com/searchUser?keyword=apple&date_posted=all-time&sort_by=relevance&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /searchVideo - Search for video by keyword
    url: https://tiktok.evelode.com/searchVideo?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /searchMusic - Search for music by keyword
    url: https://tiktok.evelode.com/searchMusic?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /searchLive - Search for live by keyword
    url: https://tiktok.evelode.com/searchLive?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /searchHashtag - Search for hashtag by keyword
    url: https://tiktok.evelode.com/searchHashtag?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getUserInfo - Get user info by profile URL or nickname
    url: https://tiktok.evelode.com/getUserInfo?query=therock&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getUserInfoByID - Get user info by profile ID
    url: https://tiktok.evelode.com/getUserInfoByID?user_id=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getBasicUserInfo - Get user info by profile ID
    url: https://tiktok.evelode.com/getBasicUserInfo?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getUserFeed - Get user feed by profile URL or nickname
    url: https://tiktok.evelode.com/getUserFeed?query=therock&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getUserFeedByID - Get user feed by profile ID
    url: https://tiktok.evelode.com/getUserFeedByID?user_id=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getUserID - Get user ID by profile URL or nickname
    url: https://tiktok.evelode.com/getUserID?query=therock&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getUsernameByID - Get username by TikTok user ID
    url: https://tiktok.evelode.com/getUsernameByID?user_id=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521 
      - 403
      - 0
  - name: /getTwitterUsername - Get Twitter username by profile URL, nickname or TikTok user ID
    url: https://tiktok.evelode.com/getTwitterUsername?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 404
      - 403
      - 0
  - name: /getInstagramUsername - Get Instagram username by profile URL, nickname or TikTok user ID
    url: https://tiktok.evelode.com/getInstagramUsername?query=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 404
      - 403
      - 0
  - name: /getYoutubeChannel - Get YouTube channel info by profile URL, nickname or TikTok user ID
    url: https://tiktok.evelode.com/getYoutubeChannel?query=6568346904743116806&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 404
      - 403
      - 0
  - name: /getFollowers - Get user followers by profile URL or nickname
    url: https://tiktok.evelode.com/getFollowers?query=diana_abissinian_cat&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getFollowersByID - Get user followers by profile ID
    url: https://tiktok.evelode.com/getFollowersByID?user_id=6950548150479684610&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getFollowing - Get user following by profile URL or nickname
    url: https://tiktok.evelode.com/getFollowing?query=diana_abissinian_cat&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getFollowingByID - Get user following by profile ID
    url: https://tiktok.evelode.com/getFollowingByID?user_id=6950548150479684610&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getHashtagInfo - Get hashtag info by URL or tag name
    url: https://tiktok.evelode.com/getHashtagInfo?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getHashtagFeed - Get hashtag feed by URL or tag name
    url: https://tiktok.evelode.com/getHashtagFeed?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getHashtagFeedByID - Get hashtag feed by ID
    url: https://tiktok.evelode.com/getHashtagFeedByID?id=13100&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getMusicInfo - Get music info by URL or ID
    url: https://tiktok.evelode.com/getMusicInfo?query=6928004115846924290&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
  - name: /getMusicFeed - Get music feed by URL or ID
    url: https://tiktok.evelode.com/getMusicFeed?query=6928004115846924290&cache_timeout=0&license_key=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    delay: 1800
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
      - 0
status-website:
  cname: tiktok-status.evelode.com
  logoUrl: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
  favicon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
  name: TikTok REST API Status
  introTitle: "**TikTok REST API Status** is the uptime monitor and status page"
  introMessage: Our status page uses a **real-time** data from [TikTok REST API](https://evelode.com/downloads/tiktok-rest-api/) servers. Starting with the [TikTok REST API](https://evelode.com/downloads/tiktok-rest-api/) – you have access to an extensive ecosystem to accelerate your development process. Built for large scale crawling, low latency high availability. Get TikTok public user data, feed, trends, hashtags, music, and non-watermarked TikTok videos.
  navbar:
    - title: Homepage
      href: /
    - title: Postman
      href: https://www.postman.com/evelode/workspace/evelode/api/e2ed8e20-0dbd-41a3-9363-092d810217ed?action=share&creator=24862082
    - title: Buy Now
      href: https://evelode.com/downloads/tiktok-rest-api/
commitMessages:
  commitAuthorName: "Evelode"
  commitAuthorEmail: "contact@evelode.com"
