owner: nextpost-tech
repo: tiktok-status

assignees:
  -  sergeykomlev

sites:
  - name: /getNoWatermarkUrl - Get non watermarked video url
    url: https://nextpost.tech/tiktok-api/getNoWatermarkUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40apple%2Fvideo%2F6994619123363876101%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getNoWatermarkUrlByID - Get non watermarked video url by video ID
    url: https://nextpost.tech/tiktok-api/getNoWatermarkUrlByID?video_id=6994619123363876101&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getVideoByID - Get video info by ID
    url: https://nextpost.tech/tiktok-api/getVideoByID?video_id=6994619123363876101&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getVideoByUrl - Get video info by URL
    url: https://nextpost.tech/tiktok-api/getVideoByUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40apple%2Fvideo%2F6994619123363876101%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getUnshortenedUrl - Convert short TikTok video URL to full TikTok video URL
    url: https://nextpost.tech/tiktok-api/getUnshortenedUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2Ft%2FZTR9YXeWQ%2F&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getCommentsByUrl - Get comments list by video URL
    url: https://nextpost.tech/tiktok-api/getCommentsByUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40onerepublic%2Fvideo%2F7141505394869898538%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getCommentsByID - Get comments list by video ID
    url: https://nextpost.tech/tiktok-api/getCommentsByID?video_id=7141505394869898538&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /searchUser - Search for user by keyword
    url: https://nextpost.tech/tiktok-api/searchUser?keyword=apple&date_posted=all-time&sort_by=relevance&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /searchVideo - Search for video by keyword
    url: https://nextpost.tech/tiktok-api/searchVideo?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /searchMusic - Search for music by keyword
    url: https://nextpost.tech/tiktok-api/searchMusic?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /searchLive - Search for live by keyword
    url: https://nextpost.tech/tiktok-api/searchLive?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /searchHashtag - Search for hashtag by keyword
    url: https://nextpost.tech/tiktok-api/searchHashtag?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521 
  - name: /getUserInfo - Get user info by profile URL or nickname
    url: https://nextpost.tech/tiktok-api/getUserInfo?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getUserInfoByID - Get user info by profile ID
    url: https://nextpost.tech/tiktok-api/getUserInfoByID?user_id=6809782522139870213&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getUserFeed - Get user feed by profile URL or nickname
    url: https://nextpost.tech/tiktok-api/getUserFeed?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getUserFeedByID - Get user feed by profile ID
    url: https://nextpost.tech/tiktok-api/getUserFeedByID?user_id=6809782522139870213&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getUserID - Get user ID by profile URL or nickname
    url: https://nextpost.tech/tiktok-api/getUserID?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getUsernameByID - Get username by TikTok user ID
    url: https://nextpost.tech/tiktok-api/getUsernameByID?user_id=6809782522139870213&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521 
  - name: /getTwitterUsername - Get Twitter username by profile URL, nickname or TikTok user ID
    url: https://nextpost.tech/tiktok-api/getTwitterUsername?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
      - 404
  - name: /getInstagramUsername - Get Instagram username by profile URL, nickname or TikTok user ID
    url: https://nextpost.tech/tiktok-api/getInstagramUsername?query=6568346904743116806&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
      - 404
  - name: /getYoutubeChannel - Get YouTube channel info by profile URL, nickname or TikTok user ID
    url: https://nextpost.tech/tiktok-api/getYoutubeChannel?query=6568346904743116806&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
      - 404
  - name: /getFollowers - Get user followers by profile URL or nickname
    url: https://nextpost.tech/tiktok-api/getFollowers?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getFollowersByID - Get user followers by profile ID
    url: https://nextpost.tech/tiktok-api/getFollowersByID?user_id=6809782522139870213&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getFollowing - Get user following by profile URL or nickname
    url: https://nextpost.tech/tiktok-api/getFollowing?query=mouse11121&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getFollowingByID - Get user following by profile ID
    url: https://nextpost.tech/tiktok-api/getFollowingByID?user_id=7073801364823966762&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getHashtagInfo - Get hashtag info by URL or tag name
    url: https://nextpost.tech/tiktok-api/getHashtagInfo?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getHashtagFeed - Get hashtag feed by URL or tag name
    url: https://nextpost.tech/tiktok-api/getHashtagFeed?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getMusicInfo - Get music info by URL or ID
    url: https://nextpost.tech/tiktok-api/getMusicInfo?query=7129970471625362182&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
  - name: /getMusicFeed - Get music feed by URL or ID
    url: https://nextpost.tech/tiktok-api/getMusicFeed?query=7129970471625362182&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521

status-website:
  cname: tiktok-status.nextpost.tech
  logoUrl: https://nextpost.tech/wp-content/uploads/2022/04/nextpost-new-logo-black.png
  favicon: https://nextpost.tech/wp-content/uploads/2021/09/cropped-nextpost.tech-new-logo-final-270x270.png
  name: Nextpost.tech TikTok REST API Status
  introTitle: "**Nextpost.tech TikTok REST API Status** is the uptime monitor and status page"
  introMessage: Our status page uses a **real-time** data from [Nextpost.tech](https://nextpost.tech) servers.
  navbar:
    - title: Homepage
      href: /
    - title: Documentation
      href: https://nextpost.tech/tiktok-rest-api-documentation/
    - title: Buy Now
      href: https://nextpost.tech/downloads/tiktok-rest-api/

commitMessages: 
  commitAuthorName: "Nextpost.tech Bot"
  commitAuthorEmail: "contact@nextpost.tech"
