owner: nextpost-tech
repo: tiktok-status

assignees:
  -  sergeykomlev

sites:
  - name: /getNoWatermarkUrl - Get non watermarked video url
    url: https://tiktok.nextpost.tech/getNoWatermarkUrl?video_url=https://www.tiktok.com/@therock/video/7106855913906081070%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503 
      - 521
      - 403
  - name: /getNoWatermarkUrlByID - Get non watermarked video url by video ID
    url: https://tiktok.nextpost.tech/getNoWatermarkUrlByID?video_id=7106855913906081070&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getVideoByID - Get video info by ID
    url: https://tiktok.nextpost.tech/getVideoByID?video_id=7106855913906081070&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getVideoByUrl - Get video info by URL
    url: https://tiktok.nextpost.tech/getVideoByUrl?video_url=https://www.tiktok.com/@therock/video/7106855913906081070%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getUnshortenedUrl - Convert short TikTok video URL to full TikTok video URL
    url: https://tiktok.nextpost.tech/getUnshortenedUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2Ft%2FZTR9YXeWQ%2F&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getCommentsByUrl - Get comments list by video URL
    url: https://tiktok.nextpost.tech/getCommentsByUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40onerepublic%2Fvideo%2F7141505394869898538%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getCommentsByID - Get comments list by video ID
    url: https://tiktok.nextpost.tech/getCommentsByID?video_id=7141505394869898538&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /searchUser - Search for user by keyword
    url: https://tiktok.nextpost.tech/searchUser?keyword=apple&date_posted=all-time&sort_by=relevance&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /searchVideo - Search for video by keyword
    url: https://tiktok.nextpost.tech/searchVideo?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /searchMusic - Search for music by keyword
    url: https://tiktok.nextpost.tech/searchMusic?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /searchLive - Search for live by keyword
    url: https://tiktok.nextpost.tech/searchLive?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /searchHashtag - Search for hashtag by keyword
    url: https://tiktok.nextpost.tech/searchHashtag?keyword=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getUserInfo - Get user info by profile URL or nickname
    url: https://tiktok.nextpost.tech/getUserInfo?query=therock&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getUserInfoByID - Get user info by profile ID
    url: https://tiktok.nextpost.tech/getUserInfoByID?user_id=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getBasicUserInfo - Get user info by profile ID
    url: https://tiktok.nextpost.tech/getBasicUserInfo?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getUserFeed - Get user feed by profile URL or nickname
    url: https://tiktok.nextpost.tech/getUserFeed?query=therock&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getUserFeedByID - Get user feed by profile ID
    url: https://tiktok.nextpost.tech/getUserFeedByID?user_id=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getUserID - Get user ID by profile URL or nickname
    url: https://tiktok.nextpost.tech/getUserID?query=therock&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getUsernameByID - Get username by TikTok user ID
    url: https://tiktok.nextpost.tech/getUsernameByID?user_id=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521 
      - 403
  - name: /getTwitterUsername - Get Twitter username by profile URL, nickname or TikTok user ID
    url: https://tiktok.nextpost.tech/getTwitterUsername?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 330000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 404
      - 403
  - name: /getInstagramUsername - Get Instagram username by profile URL, nickname or TikTok user ID
    url: https://tiktok.nextpost.tech/getInstagramUsername?query=6745191554350760966&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 404
      - 403
  - name: /getYoutubeChannel - Get YouTube channel info by profile URL, nickname or TikTok user ID
    url: https://tiktok.nextpost.tech/getYoutubeChannel?query=6568346904743116806&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 404
      - 403
  - name: /getFollowers - Get user followers by profile URL or nickname
    url: https://tiktok.nextpost.tech/getFollowers?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getFollowersByID - Get user followers by profile ID
    url: https://tiktok.nextpost.tech/getFollowersByID?user_id=6809782522139870213&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getFollowing - Get user following by profile URL or nickname
    url: https://tiktok.nextpost.tech/getFollowing?query=mouse11121&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getFollowingByID - Get user following by profile ID
    url: https://tiktok.nextpost.tech/getFollowingByID?user_id=7073801364823966762&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getHashtagInfo - Get hashtag info by URL or tag name
    url: https://tiktok.nextpost.tech/getHashtagInfo?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getHashtagFeed - Get hashtag feed by URL or tag name
    url: https://tiktok.nextpost.tech/getHashtagFeed?query=apple&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getHashtagFeedByID - Get hashtag feed by ID
    url: https://tiktok.nextpost.tech/getHashtagFeedByID?id=13100&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getMusicInfo - Get music info by URL or ID
    url: https://tiktok.nextpost.tech/getMusicInfo?query=7129970471625362182&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
  - name: /getMusicFeed - Get music feed by URL or ID
    url: https://tiktok.nextpost.tech/getMusicFeed?query=7129970471625362182&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 503
      - 521
      - 403
status-website:
  cname: tiktok-status.nextpost.tech
  logoUrl: https://nextpost.tech/wp-content/uploads/2022/04/nextpost-new-logo-black.png
  favicon: https://nextpost.tech/wp-content/uploads/2021/09/cropped-nextpost.tech-new-logo-final-270x270.png
  name: Nextpost.tech TikTok REST API Status
  introTitle: "**Nextpost.tech TikTok REST API Status** is the uptime monitor and status page"
  introMessage: Our status page uses a **real-time** data from [Nextpost.tech](https://nextpost.tech/downloads/tiktok-rest-api/) servers. Starting with the [TikTok REST API](https://nextpost.tech/downloads/tiktok-rest-api/) by Nextpost.tech – you have access to an extensive ecosystem to accelerate your development process. Built for large scale crawling, low latency high availability. Get TikTok public user data, feed, trends, hashtags, music, and non-watermarked TikTok videos.
  navbar:
    - title: Homepage
      href: /
    - title: Postman
      href: https://www.postman.com/nextpost-tech/workspace/24af3158-f1f6-4911-be7b-9c245435502f/api/e2ed8e20-0dbd-41a3-9363-092d810217ed
    - title: Buy Now
      href: https://nextpost.tech/downloads/tiktok-rest-api/
commitMessages:
  commitAuthorName: "Nextpost.tech Bot"
  commitAuthorEmail: "contact@nextpost.tech"
