owner: nextpost-tech
repo: tiktok-status

assignees:
  -  sergeykomlev

sites:
  - name: [GET] /getNoWatermarkUrl - Get non watermarked video url
    url: https://nextpost.tech/tiktok-api/getNoWatermarkUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40apple%2Fvideo%2F6994619123363876101%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
  - name: [GET] /getNoWatermarkUrlByID - Get non watermarked video url by video ID
    url: https://nextpost.tech/tiktok-api/getNoWatermarkUrlByID?video_id=6994619123363876101&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
  - name: [GET] /getVideoByID - Get video info by ID
    url: https://nextpost.tech/tiktok-api/getVideoByID?video_id=6994619123363876101&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
  - name: [GET] /getVideoByUrl - Get video info by URL
    url: https://nextpost.tech/tiktok-api/getVideoByUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40apple%2Fvideo%2F6994619123363876101%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
  - name: [GET] /getUnshortenedUrl - Convert short TikTok video URL to full TikTok video URL
    url: https://nextpost.tech/tiktok-api/getUnshortenedUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2Ft%2FZTR9YXeWQ%2F&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
  - name: [GET] /getCommentsByUrl - Get comments list by video URL
    url: https://nextpost.tech/tiktok-api/getCommentsByUrl?video_url=https%3A%2F%2Fwww.tiktok.com%2F%40onerepublic%2Fvideo%2F7141505394869898538%3Fis_copy_url%3D1%26is_from_webapp%3Dv1&cache_timeout=0&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502

status-website:
  cname: tiktok-status.nextpost.tech
  logoUrl: https://nextpost.tech/wp-content/uploads/2022/04/nextpost-new-logo-black.png
  favicon: https://nextpost.tech/wp-content/uploads/2021/09/cropped-nextpost.tech-new-logo-final-270x270.png
  name: Nextpost.tech TikTok REST API Status
  introTitle: "**Nextpost.tech TikTok REST API Status** is the uptime monitor and status page"
  introMessage: Our status page uses a **real-time** data from [Nextpost.tech](https://nextpost.tech) servers.
  navbar:
    - title: Main Page
      href: /
      
commitMessages:
  commitAuthorName: "Nextpost.tech Bot"
  commitAuthorEmail: "contact@nextpost.tech"
