owner: nextpost-tech
repo: tiktok-status

assignees:
  -  sergeykomlev

sites:
  - name: /getNoWatermarkUrl
    url: https://nextpost.tech/tiktok-api/getVideoByID?video_id=6986776740685171974&license_key=$API_KEY
    icon: https://nextpost.tech/wp-content/uploads/2021/09/cropped-nextpost.tech-new-logo-final-270x270.png
    method: GET
    maxResponseTime: 30000

status-website:
  cname: tiktok-status.nextpost.tech
  logoUrl: https://nextpost.tech/wp-content/uploads/2022/04/nextpost-new-logo-black.png
  favicon: https://nextpost.tech/wp-content/uploads/2021/09/cropped-nextpost.tech-new-logo-final-270x270.png
  name: Nextpost.tech TikTok REST API Status
  introTitle: "**Nextpost.tech TikTok REST API Status** is the uptime monitor and status page"
  introMessage: Our status page uses a **real-time** data from [Nextpost.tech](https://nextpost.tech) servers.
  navbar:
    - title: Main Page
      href: /
      
commitMessages:
  commitAuthorName: "Nextpost.tech Bot"
  commitAuthorEmail: "contact@nextpost.tech"
